# action.yml
name: 'Docker Run Action-fork'
description: 'Run a command in a new container'
inputs:
  image:
    description: 'Image'
    required: true
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: sh
  workspace_folder:
    description: 'Local directory to mount as the workspace folder in the container'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
