# action.yml
name: 'Docker Run Action-fork'
description: 'Run a command in a new container'
inputs:
  image:
    description: 'Image'
    required: true
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: bash
  workspace_folder:
    description: 'Host directory to mount as /work; if empty or /github/workspace, auto-detect from current action container mount'
    required: true
  env:
    description: 'Environment variables to set in the container, in the format VAR=value'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
